Repository CQCL/tket2, pull requests merged in 2025-04, with the labels that each got.

#827 refactor: Better error message on allocation failure.
  Cargo.lock
  Cargo.toml
  tket2-hseries/src/extension/qsystem.rs
  tket2/src/extension/bool.rs
Labels: wait to merge

#824 refactor!: Remove node parameter from Circuit
  tket2/src/circuit.rs
  tket2/src/circuit/command.rs
  tket2/src/circuit/units.rs
  tket2/src/rewrite.rs
  tket2/src/serialize.rs
Labels: breaking change

#852 feat(hseries)!: remove ZZMax operation from Qsystem extension
  tket2-exts/src/tket2_exts/data/tket2/qsystem.json
  tket2-hseries/src/extension/qsystem.rs
Labels: breaking change, wait to merge
